# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Frameworkish - Web engineering blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Web, javascript and HTML5 blog, articles about javasript frameworks and tools like
  ember, react, yeoman, webpack, test, and much more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://frameworkish.com" # the base hostname & protocol for your site
twitter_username: rastikko
github_username: Rastikko

# Build settings
markdown: kramdown
